apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "cloudflare-ddns.fullname" . }}
  labels:
    app: {{ template "cloudflare-ddns.name" . }}
    app.kubernetes.io/name: {{ template "cloudflare-ddns.name" . }}
    helm.sh/chart: {{ template "cloudflare-ddns.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.history.success }}
  failedJobsHistoryLimit: {{ .Values.history.failed }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - --log-level
                - {{ .Values.logging.level }}
              env:
                {{- if .Values.secrets.apiToken }}
                - name: CLOUDFLARE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "cloudflare-ddns.fullname" . }}-api-token
                      key: api-token
                {{- end }}
              resources:
{{ toYaml .Values.resources | indent 16 }}
              volumeMounts:
                - name: config-json
                  mountPath: /app/config.json
                  subPath: config.json
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - all
          volumes:
            - name: config-json
              configMap:
                name: {{ template "cloudflare-ddns.fullname" . }}-config-json
