name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.106"

      - name: Install dependencies
        run: make restore

      - name: Unit tests
        run: make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(make version)

      - name: Package
        run: make

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: src/cloudflare-ddns
          file: src/cloudflare-ddns/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            MINVERVERSIONOVERRIDE=${{ steps.get_version.outputs.VERSION }}
          tags: |
            ghcr.io/vandycknick/cloudflare-ddns:latest
            ghcr.io/vandycknick/cloudflare-ddns:v${{ steps.get_version.outputs.VERSION }}

      - name: Push to feedz.io
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.FEEDZ_IO_TOKEN }} --source https://f.feedz.io/nvd/cloudflare-ddns/nuget/index.json --skip-duplicate

      - name: Push to nuget
        run: dotnet nuget push artifacts/**/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts
